/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ee0e4994-ffb7-4ab5-8ce0-ea3ae389372f",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_gVi2h82Is",
    "aws_user_pools_web_client_id": "4j4j3gghuuafej63papk7k3rpv",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://6lbp4mwz6fd3lbxx6wu5cyrrnu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-eggzlwcf25ar7mnjkwfoe3efxu",
    "aws_user_files_s3_bucket": "personalfoodlogapp6e061ca7cb834c3e9af6f16468f3e95431-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
